# -*- coding: utf-8 -*-
"""
Created on Tue Jun 12 12:38:59 2018

@author: pkovacs

Even Fibonacci Numbers:

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""
a=1
b=2
fibo=[b]
while b<4000000:
    a,b = b,a+b
    if b%2==0:fibo.append(b)
print(sum(fibo))   
